export const NO_ACTION = 'NO_ACTION'
export const ERROR = 'ERROR'
export const LOADTOKEN_SUCCESS = 'LOADTOKEN_SUCCESS'
export const LOADTOKEN_ERROR = 'LOADTOKEN_ERROR'

export const LOAD_INVITATION = 'LOAD_INVITATION'
export const LOAD_INVITATION_SUCCESS = 'LOAD_INVITATION_SUCCESS'
export const ADD_NEW_TAG = 'ADD_NEW_TAG'

export const LOAD_COUNTRIES = 'LOAD_COUNTRIES'
export const LOAD_COUNTRIES_SUCCESS = 'LOAD_COUNTRIES_SUCCESS'

export const CHOOSE_TAGS = 'CHOOSE_TAGS'